# PROJECT INFORMATION
site_name: !ENV [SITE_NAME, 'Phoenix Biorhythm Platform']
site_author: Christopher Adams

repo_url: https://github.com/cadams4341/phoenix-biorhythm-platform

edit_uri: null

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://cadams4341.github.io/phoenix-biorhythm-platform">Phoenix Biorhythm Platform</a> by <span property="cc:attributionName">Christopher Adams</span> is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p>

# DOCUMENTATION LAYOUT
nav:
  - Home: index.md
  - Vision: vision/abstract.md
  - Glossary: glossary/index.md
  - About the Site: about/index.md

not_in_nav: |
  about/macros-info.md
  snippets/chronobiology-glossary.md
  snippets/hero-image.md
  snippets/hide-title.md
  snippets/swe-glossary.md

# BUILD DIRECTORIES
theme:
  name: material
  locale: en
  font:
    text: Cabin
    code: Ubuntu Mono
  favicon: images/circadian-rhythms-32x32.png
  logo: images/circadian-rhythms-white.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - toc.follow

# FORMATTING OPTIONS
markdown_extensions:  # see https://squidfunk.github.io/mkdocs-material/setup/extensions/
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.md_in_html
  - markdown.extensions.meta
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.tab:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      type: custom
      custom_format: "%Y-%m-%d %H:%M:%S%z (%Z)"
      locale: en
      timezone: US/Central
  - macros
  - privacy:
      enabled: !ENV [CI, false]   # needs to be enabled at some point
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/hero-image.css
  - stylesheets/typeset.css

